services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: blog
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:5.2.1
    restart: always
    ports:
      - "3307:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306